import type { StaffMember, Ticket, Todo } from "./types";

export const tickets: Ticket[] = [
  {
    id: 101,
    user: "alice@brrmedia.co.uk",
    issue: "Hardware",
    description: "My laptop won't turn on after the recent update",
    status: "Open",
    created: "2025-05-16T09:30:00Z",
  },
  {
    id: 102,
    user: "bob@brrmedia.co.uk",
    issue: "Software",
    description: "Need access to the design software suite",
    status: "In Progress",
    created: "2025-05-10T14:15:00Z",
  },
  {
    id: 103,
    user: "dave@brrmedia.co.uk",
    issue: "Network",
    description: "Cannot connect to the company VPN from home",
    status: "Resolved",
    created: "2025-05-08T11:45:00Z",
  },
  {
    id: 104,
    user: "joe@brrmedia.co.uk",
    issue: "Account",
    description: "Need to reset my password for the CRM system",
    status: "Open",
    created: "2025-05-01T16:20:00Z",
  },
  {
    id: 105,
    user: "mohamed@brrmedia.co.uk",
    issue: "React developer",
    description: "Need a React frontend developer",
    status: "In Progress",
    created: "2025-05-07T10:00:00Z",
  },
  {
    id: 106,
    user: "andy@brrmedia.co.uk",
    issue: "Hardware",
    description: "Request for a second monitor for my workstation",
    status: "In Progress",
    created: "2025-05-07T18:10:00Z",
  },
];

export const todos: Todo[] = [
  {
    id: "1",
    title: "Complete project documentation",
    completed: false,
  },
  {
    id: "2",
    title: "Review pull requests",
    completed: true,
  },
  {
    id: "3",
    title: "Prepare for team meeting",
    completed: false,
  },
  {
    id: "4",
    title: "Complete dashboard project",
    completed: true,
  },
  {
    id: "5",
    title: "Update system",
    completed: false,
  },
];

export const staffMembers: StaffMember[] = [
  {
    id: 1,
    name: "John Doe",
    role: "Software Developer",
    email: "jdoe@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-16T09:30:00Z",
    driveUsage: "2.3 GB",
    device: "MacBook Pro",
  },
  {
    id: 2,
    name: "Mohamed Virji",
    role: "Head of Technology",
    email: "mvirji@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-15T17:15:00Z",
    driveUsage: "1.7 GB",
    device: "Windows PC",
  },
  {
    id: 3,
    name: "Robert Johnson",
    role: "UI/UX Designer",
    email: "rjohnson@brrmedia.co.uk",
    status: "inactive",
    lastLogin: "2025-05-13T10:00:00Z",
    driveUsage: "4.1 GB",
    device: "iPad Pro",
  },
  {
    id: 4,
    name: "Emily Davis",
    role: "QA Engineer",
    email: "edavis@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-16T11:45:00Z",
    driveUsage: "0.8 GB",
    device: "Dell XPS",
  },
  {
    id: 5,
    name: "Michael Wilson",
    role: "DevOps Engineer",
    email: "mwilson@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-16T10:20:00Z",
    driveUsage: "3.5 GB",
    device: "ThinkPad",
  },
  {
    id: 6,
    name: "Sarah Brown",
    role: "Data Analyst",
    email: "sbrown@brrmedia.co.uk",
    status: "inactive",
    lastLogin: "2025-05-09T08:00:00Z",
    driveUsage: "2.9 GB",
    device: "Surface Pro",
  },
];
